name: Regularly update the CSV file


on:
  schedule:
    - cron: '1 2 * * 1'
  workflow_dispatch:

jobs:
  build:
    name: update CSV
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions//checkout@v3
      - name: download
        run: curl -LO https://www8.cao.go.jp/chosei/shukujitsu/syukujitsu.csv --output ./assets/syukujitsu.csv
      - name: commit & push changes
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
        env:
          CI_COMMIT_AUTHOR: github-actions
          CI_COMMIT_MESSAGE: update csv from github action
        run: |
          git config --global user.name "${{ env.CI_COMMIT_AUTHOR }}"
          git add .
          git commit -m "${{ env.CI_COMMIT_MESSAGE }}"
          git pull
          git push origin main
