name: Regularly update the CSV file


on:
  schedule:
    - cron: '1 2 * * 1'
  workflow_dispatch:

jobs:
  build:
    name: update CSV
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: download
        run: cargo run -g=true
      - name: commit & push changes
        env:
          CI_COMMIT_AUTHOR: github-actions
          CI_COMMIT_MESSAGE: update dates.rs from github action
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          author_name: ${{ env.CI_COMMIT_AUTHOR }}
          message: ${{ env.CI_COMMIT_MESSAGE }}

